// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IDT.Data;

namespace IDT.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201106164426_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactDemoNC.Models.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "create"
                        },
                        new
                        {
                            Id = 2,
                            Action = "make"
                        },
                        new
                        {
                            Id = 3,
                            Action = "produce"
                        },
                        new
                        {
                            Id = 4,
                            Action = "invent"
                        },
                        new
                        {
                            Id = 5,
                            Action = "construct"
                        },
                        new
                        {
                            Id = 6,
                            Action = "defile"
                        },
                        new
                        {
                            Id = 7,
                            Action = "collaborate with"
                        },
                        new
                        {
                            Id = 8,
                            Action = "calculate"
                        },
                        new
                        {
                            Id = 9,
                            Action = "build"
                        },
                        new
                        {
                            Id = 10,
                            Action = "watch"
                        },
                        new
                        {
                            Id = 11,
                            Action = "count"
                        },
                        new
                        {
                            Id = 12,
                            Action = "predict"
                        },
                        new
                        {
                            Id = 13,
                            Action = "distribute"
                        },
                        new
                        {
                            Id = 14,
                            Action = "collect"
                        },
                        new
                        {
                            Id = 15,
                            Action = "spam"
                        },
                        new
                        {
                            Id = 16,
                            Action = "hack"
                        },
                        new
                        {
                            Id = 17,
                            Action = "breack"
                        },
                        new
                        {
                            Id = 18,
                            Action = "fix"
                        },
                        new
                        {
                            Id = 19,
                            Action = "clear"
                        },
                        new
                        {
                            Id = 20,
                            Action = "write down"
                        });
                });

            modelBuilder.Entity("ReactDemoNC.Models.Actors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actor = "developers"
                        },
                        new
                        {
                            Id = 2,
                            Actor = "men"
                        },
                        new
                        {
                            Id = 3,
                            Actor = "devOps"
                        },
                        new
                        {
                            Id = 4,
                            Actor = "data scientists"
                        },
                        new
                        {
                            Id = 5,
                            Actor = "business analysts"
                        },
                        new
                        {
                            Id = 6,
                            Actor = "cloud сomputing experts"
                        },
                        new
                        {
                            Id = 7,
                            Actor = "data engineers"
                        },
                        new
                        {
                            Id = 8,
                            Actor = "fullstack-developers"
                        },
                        new
                        {
                            Id = 9,
                            Actor = "IoT specialists"
                        },
                        new
                        {
                            Id = 10,
                            Actor = "network administrators"
                        },
                        new
                        {
                            Id = 11,
                            Actor = "information security specialists"
                        },
                        new
                        {
                            Id = 12,
                            Actor = "HR managers"
                        },
                        new
                        {
                            Id = 13,
                            Actor = "sales managers"
                        },
                        new
                        {
                            Id = 14,
                            Actor = "account managers"
                        },
                        new
                        {
                            Id = 15,
                            Actor = "project managers"
                        },
                        new
                        {
                            Id = 16,
                            Actor = "copywriters"
                        },
                        new
                        {
                            Id = 17,
                            Actor = "game writers"
                        },
                        new
                        {
                            Id = 18,
                            Actor = "3D Modelers"
                        },
                        new
                        {
                            Id = 19,
                            Actor = "animators"
                        },
                        new
                        {
                            Id = 20,
                            Actor = "art directors"
                        });
                });

            modelBuilder.Entity("ReactDemoNC.Models.Additions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Additions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Addition = "big data analytics"
                        },
                        new
                        {
                            Id = 2,
                            Addition = "calculations for the construction of an intergalactic ship"
                        },
                        new
                        {
                            Id = 3,
                            Addition = "puppy registration database"
                        },
                        new
                        {
                            Id = 4,
                            Addition = "skyscrapers"
                        },
                        new
                        {
                            Id = 5,
                            Addition = "warehouses with Formula 1 cars"
                        },
                        new
                        {
                            Id = 6,
                            Addition = "artificial intelligence robots"
                        },
                        new
                        {
                            Id = 7,
                            Addition = "digital twin"
                        },
                        new
                        {
                            Id = 8,
                            Addition = "virtual reality wars"
                        },
                        new
                        {
                            Id = 9,
                            Addition = "distributed data chain"
                        },
                        new
                        {
                            Id = 10,
                            Addition = "adaptive security architecture"
                        },
                        new
                        {
                            Id = 11,
                            Addition = "deadly virus distribution maps"
                        },
                        new
                        {
                            Id = 12,
                            Addition = "route for pizza delivery men"
                        },
                        new
                        {
                            Id = 13,
                            Addition = "circuits for electronic boards"
                        },
                        new
                        {
                            Id = 14,
                            Addition = "discounts on aliexpress"
                        },
                        new
                        {
                            Id = 15,
                            Addition = "fun days on vacation"
                        },
                        new
                        {
                            Id = 16,
                            Addition = "invisible force that cleans the house"
                        },
                        new
                        {
                            Id = 17,
                            Addition = "mining of endless energy"
                        },
                        new
                        {
                            Id = 18,
                            Addition = "birthday scenarios"
                        },
                        new
                        {
                            Id = 19,
                            Addition = "potatoes in the village"
                        },
                        new
                        {
                            Id = 20,
                            Addition = "works of art"
                        });
                });

            modelBuilder.Entity("ReactDemoNC.Models.Templates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Template = "Implement application using {techStack} allowing {actor} {action} {addition}."
                        },
                        new
                        {
                            Id = 2,
                            Template = "Using {techStack} implement an application allowing {actor} {action} {addition}."
                        },
                        new
                        {
                            Id = 3,
                            Template = "With the help of {techStack} implement an application allowing {actor} {action} {addition}."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
